### ISSUE TITLE
Aarch builds corrupted?

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/pypy3.6-feedstock#83]
The following is appearing in https://github.com/conda-forge/numpy-feedstock/pull/272, even after a restart:
```
SafetyError: The package for pypy3.8 located at /home/conda/feedstock_root/build_artifacts/pkg_cache/pypy3.8-7.3.9-hfb6fae5_1
appears to be corrupted. The path 'bin/pypy3'
has an incorrect size.
  reported size: 6192 bytes
  actual size: 2639 bytes
```

**Comment by h-vetinari** [comment]
Which is surprising, because there hasn't been any (visible) change in the [artefacts](https://anaconda.org/conda-forge/pypy3.8/files).

**Comment by xhochy** [comment]
Also seeing this in https://github.com/conda-forge/pyppmd-feedstock/pull/22

**Comment by chrisburr** [comment]
This is being discussed on gitter at: https://gitter.im/conda-forge/conda-forge.github.io?at=62b468f2904f20479a190b5b

The cause is a combination of:
* conda using hardlinks when installing
* crossenv/cross-python applying it's hacky fixes to make a cross-compilation environment

**Comment by h-vetinari** [comment]
Confirming as fixed by https://github.com/conda-forge/cross-python-feedstock/pull/44

**Comment by xylar** [comment]
@chrisburr and others, I'm still seeing this in:
https://github.com/conda-forge/keyring-feedstock/pull/88
```
SafetyError: The package for pypy3.7 located at /home/conda/feedstock_root/build_artifacts/pkg_cache/pypy3.7-7.3.7-h7cff6a8_2
appears to be corrupted. The path 'bin/pypy3'
has an incorrect size.
  reported size: 6152 bytes
  actual size: 2653 bytes
```
Am I doing something weird there or is this issue not completely fixed yet?

**Comment by traversaro** [comment]
We had a similar error in https://github.com/conda-forge/hpp-fcl-feedstock/pull/65 as well.

**Comment by xylar** [comment]
@chrisburr, are you able to apply the fix that you had for pypy 3.8 and 3.9 to pypy 3.7 for feedstocks that have not yet been able to migrate.

**Comment by chrisburr** [comment]
PyPy 3.7 isn't supported by conda-forge anymore so I can't easily.

It's probably possible to hack together something to get `conda-forge/cross-python-feedstock` to build for PyPy 3.7 again if someone is sufficiently motivated though I'm not going to be able to dedicate time to it. The best solution is probably to remove the PyPy 3.7 migration from feedstocks that haven't been able to accept the PyPy 3.8+3.9 migration.

**Comment by traversaro** [comment]
Yes, I suggested something similar in the PR, as I do not think there are a lot of pypy37 + aarch/ppc64 users at all.
